// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2GkB3D9QTJ7iG4ObEEc8ZpUG6ydkqlFI',
    appId: '1:521895754222:android:0a99ced6603bb8fa0eb6ff',
    messagingSenderId: '521895754222',
    projectId: 'pushnotificationsample-21177',
    databaseURL: 'https://pushnotificationsample-21177-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'pushnotificationsample-21177.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8NX0o7XllEt7MMYE6htGs89nI4IsTPj8',
    appId: '1:521895754222:ios:3ed2901c52eb43390eb6ff',
    messagingSenderId: '521895754222',
    projectId: 'pushnotificationsample-21177',
    databaseURL: 'https://pushnotificationsample-21177-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'pushnotificationsample-21177.appspot.com',
    iosBundleId: 'com.example.flutterFirebasePushNotification',
  );

}